spring.application.name=DartVader

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/Dev-DartVader

public.auth.config.authority=http://localhost:8081/realms/Dev-DartVader
public.auth.config.client-id=dev-frontend
public.auth.config.scope=openid
public.auth.config.responseType=code

server.servlet.context-path=/api